# Define docker image
FROM python:3.8
# Define working directory
WORKDIR /containerising_docker/example2_print_input_message
# Copy into working directory
COPY . /containerising_docker/example2_print_input_message
# Run commands
CMD ["python", "print_f_input.py"]
