# define Docker image
FROM python:3.8
# Define present working directory
WORKDIR /containerising_docker/example1_print_function
# Copy file into working directory
COPY . /containerising_docker/example1_print_function
# Define commands to run when starting container
CMD ["python", "print_f.py"]